- Numpy internally store datas continous block of memory independednt of pythons objects
- numpy algorithms are written in C
- can operate directly on memeory without overhead of typechecking
- uses much less memeory

- performs actions on entire array without the need for loops

In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 15.6 ms, sys: 19.1 ms, total: 34.7 ms
Wall time: 36.3 ms


In [5]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 714 ms, sys: 143 ms, total: 858 ms
Wall time: 859 ms


### Here its visible the efficiency of using numpy over the regular pthon code

## ndarray

nd array is a generic multidimensional conatainer for data of same type(homogenous). 
each array has a. shape, tuple indicating size of each dimension and dtype

In [6]:
import numpy as np
# Generate random
data = np.random.randn(2,3)
data

array([[ 1.51739961, -0.15281173,  0.87736639],
       [ 0.00825936,  0.34722864, -0.06233685]])

In [7]:
data * 10

array([[15.17399613, -1.52811733,  8.77366391],
       [ 0.08259358,  3.47228643, -0.62336846]])

In [8]:
data + data

array([[ 3.03479923, -0.30562347,  1.75473278],
       [ 0.01651872,  0.69445729, -0.12467369]])

#### creation

In [9]:
data1 = [6, 7.5, 8, 0, 1]
array1 = np.array(data1)
array1 # 1D Array

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1,2,3,4], [5,6,7,8]]
array2 = np.array(data2)
array2 # 2D array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Dimension

In [14]:
array2.ndim

2

#### shape

In [15]:
array2.shape

(2, 4)

#### dtype

In [16]:
array2.dtype

dtype('int64')

### creating zero matrix


In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Emtpy matrix (does not initialize values)

In [24]:
np.empty([2, 2], dtype=int)

array([[4618441417868443648, 4620130267728707584],
       [4620693217682128896, 4607182418800017408]])